apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v9qx7jqhi-python 
  janus-idp.io/tekton: v9qx7jqhi-python
  backstage.io/kubernetes-id: v9qx7jqhi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v9qx7jqhi-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml